/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: conf.proto */

#ifndef PROTOBUF_C_conf_2eproto__INCLUDED
#define PROTOBUF_C_conf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Conf__CreateSchemaReq Conf__CreateSchemaReq;
typedef struct _Conf__CreateSchemaResp Conf__CreateSchemaResp;
typedef struct _Conf__QuerySchemaReq Conf__QuerySchemaReq;
typedef struct _Conf__QuerySchemaResp Conf__QuerySchemaResp;
typedef struct _Conf__DeleteSchemaReq Conf__DeleteSchemaReq;
typedef struct _Conf__DeleteSchemaResp Conf__DeleteSchemaResp;
typedef struct _Conf__PutConfReq Conf__PutConfReq;
typedef struct _Conf__PutConfResp Conf__PutConfResp;
typedef struct _Conf__GetConfReq Conf__GetConfReq;
typedef struct _Conf__GetConfResp Conf__GetConfResp;
typedef struct _Conf__DeleteConfReq Conf__DeleteConfReq;
typedef struct _Conf__DeleteConfResp Conf__DeleteConfResp;


/* --- enums --- */


/* --- messages --- */

struct  _Conf__CreateSchemaReq
{
  ProtobufCMessage base;
  char *name;
};
#define CONF__CREATE_SCHEMA_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__create_schema_req__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Conf__CreateSchemaResp
{
  ProtobufCMessage base;
  char *name;
  int32_t code;
  char *msg;
};
#define CONF__CREATE_SCHEMA_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__create_schema_resp__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  _Conf__QuerySchemaReq
{
  ProtobufCMessage base;
  char *name;
};
#define CONF__QUERY_SCHEMA_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__query_schema_req__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Conf__QuerySchemaResp
{
  ProtobufCMessage base;
  char *name;
  size_t n_confs;
  char **confs;
};
#define CONF__QUERY_SCHEMA_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__query_schema_resp__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _Conf__DeleteSchemaReq
{
  ProtobufCMessage base;
  char *name;
};
#define CONF__DELETE_SCHEMA_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__delete_schema_req__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Conf__DeleteSchemaResp
{
  ProtobufCMessage base;
  char *name;
  char *msg;
};
#define CONF__DELETE_SCHEMA_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__delete_schema_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Conf__PutConfReq
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
  char *conf_val;
};
#define CONF__PUT_CONF_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__put_conf_req__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Conf__PutConfResp
{
  ProtobufCMessage base;
  char *schema_name;
  char *msg;
};
#define CONF__PUT_CONF_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__put_conf_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Conf__GetConfReq
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
};
#define CONF__GET_CONF_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__get_conf_req__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Conf__GetConfResp
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
  char *conf_val;
};
#define CONF__GET_CONF_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__get_conf_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Conf__DeleteConfReq
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
};
#define CONF__DELETE_CONF_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__delete_conf_req__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Conf__DeleteConfResp
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
  char *conf_val;
};
#define CONF__DELETE_CONF_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&conf__delete_conf_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Conf__CreateSchemaReq methods */
void   conf__create_schema_req__init
                     (Conf__CreateSchemaReq         *message);
size_t conf__create_schema_req__get_packed_size
                     (const Conf__CreateSchemaReq   *message);
size_t conf__create_schema_req__pack
                     (const Conf__CreateSchemaReq   *message,
                      uint8_t             *out);
size_t conf__create_schema_req__pack_to_buffer
                     (const Conf__CreateSchemaReq   *message,
                      ProtobufCBuffer     *buffer);
Conf__CreateSchemaReq *
       conf__create_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__create_schema_req__free_unpacked
                     (Conf__CreateSchemaReq *message,
                      ProtobufCAllocator *allocator);
/* Conf__CreateSchemaResp methods */
void   conf__create_schema_resp__init
                     (Conf__CreateSchemaResp         *message);
size_t conf__create_schema_resp__get_packed_size
                     (const Conf__CreateSchemaResp   *message);
size_t conf__create_schema_resp__pack
                     (const Conf__CreateSchemaResp   *message,
                      uint8_t             *out);
size_t conf__create_schema_resp__pack_to_buffer
                     (const Conf__CreateSchemaResp   *message,
                      ProtobufCBuffer     *buffer);
Conf__CreateSchemaResp *
       conf__create_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__create_schema_resp__free_unpacked
                     (Conf__CreateSchemaResp *message,
                      ProtobufCAllocator *allocator);
/* Conf__QuerySchemaReq methods */
void   conf__query_schema_req__init
                     (Conf__QuerySchemaReq         *message);
size_t conf__query_schema_req__get_packed_size
                     (const Conf__QuerySchemaReq   *message);
size_t conf__query_schema_req__pack
                     (const Conf__QuerySchemaReq   *message,
                      uint8_t             *out);
size_t conf__query_schema_req__pack_to_buffer
                     (const Conf__QuerySchemaReq   *message,
                      ProtobufCBuffer     *buffer);
Conf__QuerySchemaReq *
       conf__query_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__query_schema_req__free_unpacked
                     (Conf__QuerySchemaReq *message,
                      ProtobufCAllocator *allocator);
/* Conf__QuerySchemaResp methods */
void   conf__query_schema_resp__init
                     (Conf__QuerySchemaResp         *message);
size_t conf__query_schema_resp__get_packed_size
                     (const Conf__QuerySchemaResp   *message);
size_t conf__query_schema_resp__pack
                     (const Conf__QuerySchemaResp   *message,
                      uint8_t             *out);
size_t conf__query_schema_resp__pack_to_buffer
                     (const Conf__QuerySchemaResp   *message,
                      ProtobufCBuffer     *buffer);
Conf__QuerySchemaResp *
       conf__query_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__query_schema_resp__free_unpacked
                     (Conf__QuerySchemaResp *message,
                      ProtobufCAllocator *allocator);
/* Conf__DeleteSchemaReq methods */
void   conf__delete_schema_req__init
                     (Conf__DeleteSchemaReq         *message);
size_t conf__delete_schema_req__get_packed_size
                     (const Conf__DeleteSchemaReq   *message);
size_t conf__delete_schema_req__pack
                     (const Conf__DeleteSchemaReq   *message,
                      uint8_t             *out);
size_t conf__delete_schema_req__pack_to_buffer
                     (const Conf__DeleteSchemaReq   *message,
                      ProtobufCBuffer     *buffer);
Conf__DeleteSchemaReq *
       conf__delete_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__delete_schema_req__free_unpacked
                     (Conf__DeleteSchemaReq *message,
                      ProtobufCAllocator *allocator);
/* Conf__DeleteSchemaResp methods */
void   conf__delete_schema_resp__init
                     (Conf__DeleteSchemaResp         *message);
size_t conf__delete_schema_resp__get_packed_size
                     (const Conf__DeleteSchemaResp   *message);
size_t conf__delete_schema_resp__pack
                     (const Conf__DeleteSchemaResp   *message,
                      uint8_t             *out);
size_t conf__delete_schema_resp__pack_to_buffer
                     (const Conf__DeleteSchemaResp   *message,
                      ProtobufCBuffer     *buffer);
Conf__DeleteSchemaResp *
       conf__delete_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__delete_schema_resp__free_unpacked
                     (Conf__DeleteSchemaResp *message,
                      ProtobufCAllocator *allocator);
/* Conf__PutConfReq methods */
void   conf__put_conf_req__init
                     (Conf__PutConfReq         *message);
size_t conf__put_conf_req__get_packed_size
                     (const Conf__PutConfReq   *message);
size_t conf__put_conf_req__pack
                     (const Conf__PutConfReq   *message,
                      uint8_t             *out);
size_t conf__put_conf_req__pack_to_buffer
                     (const Conf__PutConfReq   *message,
                      ProtobufCBuffer     *buffer);
Conf__PutConfReq *
       conf__put_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__put_conf_req__free_unpacked
                     (Conf__PutConfReq *message,
                      ProtobufCAllocator *allocator);
/* Conf__PutConfResp methods */
void   conf__put_conf_resp__init
                     (Conf__PutConfResp         *message);
size_t conf__put_conf_resp__get_packed_size
                     (const Conf__PutConfResp   *message);
size_t conf__put_conf_resp__pack
                     (const Conf__PutConfResp   *message,
                      uint8_t             *out);
size_t conf__put_conf_resp__pack_to_buffer
                     (const Conf__PutConfResp   *message,
                      ProtobufCBuffer     *buffer);
Conf__PutConfResp *
       conf__put_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__put_conf_resp__free_unpacked
                     (Conf__PutConfResp *message,
                      ProtobufCAllocator *allocator);
/* Conf__GetConfReq methods */
void   conf__get_conf_req__init
                     (Conf__GetConfReq         *message);
size_t conf__get_conf_req__get_packed_size
                     (const Conf__GetConfReq   *message);
size_t conf__get_conf_req__pack
                     (const Conf__GetConfReq   *message,
                      uint8_t             *out);
size_t conf__get_conf_req__pack_to_buffer
                     (const Conf__GetConfReq   *message,
                      ProtobufCBuffer     *buffer);
Conf__GetConfReq *
       conf__get_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__get_conf_req__free_unpacked
                     (Conf__GetConfReq *message,
                      ProtobufCAllocator *allocator);
/* Conf__GetConfResp methods */
void   conf__get_conf_resp__init
                     (Conf__GetConfResp         *message);
size_t conf__get_conf_resp__get_packed_size
                     (const Conf__GetConfResp   *message);
size_t conf__get_conf_resp__pack
                     (const Conf__GetConfResp   *message,
                      uint8_t             *out);
size_t conf__get_conf_resp__pack_to_buffer
                     (const Conf__GetConfResp   *message,
                      ProtobufCBuffer     *buffer);
Conf__GetConfResp *
       conf__get_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__get_conf_resp__free_unpacked
                     (Conf__GetConfResp *message,
                      ProtobufCAllocator *allocator);
/* Conf__DeleteConfReq methods */
void   conf__delete_conf_req__init
                     (Conf__DeleteConfReq         *message);
size_t conf__delete_conf_req__get_packed_size
                     (const Conf__DeleteConfReq   *message);
size_t conf__delete_conf_req__pack
                     (const Conf__DeleteConfReq   *message,
                      uint8_t             *out);
size_t conf__delete_conf_req__pack_to_buffer
                     (const Conf__DeleteConfReq   *message,
                      ProtobufCBuffer     *buffer);
Conf__DeleteConfReq *
       conf__delete_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__delete_conf_req__free_unpacked
                     (Conf__DeleteConfReq *message,
                      ProtobufCAllocator *allocator);
/* Conf__DeleteConfResp methods */
void   conf__delete_conf_resp__init
                     (Conf__DeleteConfResp         *message);
size_t conf__delete_conf_resp__get_packed_size
                     (const Conf__DeleteConfResp   *message);
size_t conf__delete_conf_resp__pack
                     (const Conf__DeleteConfResp   *message,
                      uint8_t             *out);
size_t conf__delete_conf_resp__pack_to_buffer
                     (const Conf__DeleteConfResp   *message,
                      ProtobufCBuffer     *buffer);
Conf__DeleteConfResp *
       conf__delete_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   conf__delete_conf_resp__free_unpacked
                     (Conf__DeleteConfResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Conf__CreateSchemaReq_Closure)
                 (const Conf__CreateSchemaReq *message,
                  void *closure_data);
typedef void (*Conf__CreateSchemaResp_Closure)
                 (const Conf__CreateSchemaResp *message,
                  void *closure_data);
typedef void (*Conf__QuerySchemaReq_Closure)
                 (const Conf__QuerySchemaReq *message,
                  void *closure_data);
typedef void (*Conf__QuerySchemaResp_Closure)
                 (const Conf__QuerySchemaResp *message,
                  void *closure_data);
typedef void (*Conf__DeleteSchemaReq_Closure)
                 (const Conf__DeleteSchemaReq *message,
                  void *closure_data);
typedef void (*Conf__DeleteSchemaResp_Closure)
                 (const Conf__DeleteSchemaResp *message,
                  void *closure_data);
typedef void (*Conf__PutConfReq_Closure)
                 (const Conf__PutConfReq *message,
                  void *closure_data);
typedef void (*Conf__PutConfResp_Closure)
                 (const Conf__PutConfResp *message,
                  void *closure_data);
typedef void (*Conf__GetConfReq_Closure)
                 (const Conf__GetConfReq *message,
                  void *closure_data);
typedef void (*Conf__GetConfResp_Closure)
                 (const Conf__GetConfResp *message,
                  void *closure_data);
typedef void (*Conf__DeleteConfReq_Closure)
                 (const Conf__DeleteConfReq *message,
                  void *closure_data);
typedef void (*Conf__DeleteConfResp_Closure)
                 (const Conf__DeleteConfResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor conf__create_schema_req__descriptor;
extern const ProtobufCMessageDescriptor conf__create_schema_resp__descriptor;
extern const ProtobufCMessageDescriptor conf__query_schema_req__descriptor;
extern const ProtobufCMessageDescriptor conf__query_schema_resp__descriptor;
extern const ProtobufCMessageDescriptor conf__delete_schema_req__descriptor;
extern const ProtobufCMessageDescriptor conf__delete_schema_resp__descriptor;
extern const ProtobufCMessageDescriptor conf__put_conf_req__descriptor;
extern const ProtobufCMessageDescriptor conf__put_conf_resp__descriptor;
extern const ProtobufCMessageDescriptor conf__get_conf_req__descriptor;
extern const ProtobufCMessageDescriptor conf__get_conf_resp__descriptor;
extern const ProtobufCMessageDescriptor conf__delete_conf_req__descriptor;
extern const ProtobufCMessageDescriptor conf__delete_conf_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_conf_2eproto__INCLUDED */
