/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: conf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "conf.pb-c.h"
void   conf__create_schema_req__init
                     (Conf__CreateSchemaReq         *message)
{
  static const Conf__CreateSchemaReq init_value = CONF__CREATE_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t conf__create_schema_req__get_packed_size
                     (const Conf__CreateSchemaReq *message)
{
  assert(message->base.descriptor == &conf__create_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__create_schema_req__pack
                     (const Conf__CreateSchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__create_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__create_schema_req__pack_to_buffer
                     (const Conf__CreateSchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__create_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__CreateSchemaReq *
       conf__create_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__CreateSchemaReq *)
     protobuf_c_message_unpack (&conf__create_schema_req__descriptor,
                                allocator, len, data);
}
void   conf__create_schema_req__free_unpacked
                     (Conf__CreateSchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__create_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__create_schema_resp__init
                     (Conf__CreateSchemaResp         *message)
{
  static const Conf__CreateSchemaResp init_value = CONF__CREATE_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t conf__create_schema_resp__get_packed_size
                     (const Conf__CreateSchemaResp *message)
{
  assert(message->base.descriptor == &conf__create_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__create_schema_resp__pack
                     (const Conf__CreateSchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__create_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__create_schema_resp__pack_to_buffer
                     (const Conf__CreateSchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__create_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__CreateSchemaResp *
       conf__create_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__CreateSchemaResp *)
     protobuf_c_message_unpack (&conf__create_schema_resp__descriptor,
                                allocator, len, data);
}
void   conf__create_schema_resp__free_unpacked
                     (Conf__CreateSchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__create_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__query_schema_req__init
                     (Conf__QuerySchemaReq         *message)
{
  static const Conf__QuerySchemaReq init_value = CONF__QUERY_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t conf__query_schema_req__get_packed_size
                     (const Conf__QuerySchemaReq *message)
{
  assert(message->base.descriptor == &conf__query_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__query_schema_req__pack
                     (const Conf__QuerySchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__query_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__query_schema_req__pack_to_buffer
                     (const Conf__QuerySchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__query_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__QuerySchemaReq *
       conf__query_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__QuerySchemaReq *)
     protobuf_c_message_unpack (&conf__query_schema_req__descriptor,
                                allocator, len, data);
}
void   conf__query_schema_req__free_unpacked
                     (Conf__QuerySchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__query_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__query_schema_resp__init
                     (Conf__QuerySchemaResp         *message)
{
  static const Conf__QuerySchemaResp init_value = CONF__QUERY_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t conf__query_schema_resp__get_packed_size
                     (const Conf__QuerySchemaResp *message)
{
  assert(message->base.descriptor == &conf__query_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__query_schema_resp__pack
                     (const Conf__QuerySchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__query_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__query_schema_resp__pack_to_buffer
                     (const Conf__QuerySchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__query_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__QuerySchemaResp *
       conf__query_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__QuerySchemaResp *)
     protobuf_c_message_unpack (&conf__query_schema_resp__descriptor,
                                allocator, len, data);
}
void   conf__query_schema_resp__free_unpacked
                     (Conf__QuerySchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__query_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__delete_schema_req__init
                     (Conf__DeleteSchemaReq         *message)
{
  static const Conf__DeleteSchemaReq init_value = CONF__DELETE_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t conf__delete_schema_req__get_packed_size
                     (const Conf__DeleteSchemaReq *message)
{
  assert(message->base.descriptor == &conf__delete_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__delete_schema_req__pack
                     (const Conf__DeleteSchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__delete_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__delete_schema_req__pack_to_buffer
                     (const Conf__DeleteSchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__delete_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__DeleteSchemaReq *
       conf__delete_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__DeleteSchemaReq *)
     protobuf_c_message_unpack (&conf__delete_schema_req__descriptor,
                                allocator, len, data);
}
void   conf__delete_schema_req__free_unpacked
                     (Conf__DeleteSchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__delete_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__delete_schema_resp__init
                     (Conf__DeleteSchemaResp         *message)
{
  static const Conf__DeleteSchemaResp init_value = CONF__DELETE_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t conf__delete_schema_resp__get_packed_size
                     (const Conf__DeleteSchemaResp *message)
{
  assert(message->base.descriptor == &conf__delete_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__delete_schema_resp__pack
                     (const Conf__DeleteSchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__delete_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__delete_schema_resp__pack_to_buffer
                     (const Conf__DeleteSchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__delete_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__DeleteSchemaResp *
       conf__delete_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__DeleteSchemaResp *)
     protobuf_c_message_unpack (&conf__delete_schema_resp__descriptor,
                                allocator, len, data);
}
void   conf__delete_schema_resp__free_unpacked
                     (Conf__DeleteSchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__delete_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__put_conf_req__init
                     (Conf__PutConfReq         *message)
{
  static const Conf__PutConfReq init_value = CONF__PUT_CONF_REQ__INIT;
  *message = init_value;
}
size_t conf__put_conf_req__get_packed_size
                     (const Conf__PutConfReq *message)
{
  assert(message->base.descriptor == &conf__put_conf_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__put_conf_req__pack
                     (const Conf__PutConfReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__put_conf_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__put_conf_req__pack_to_buffer
                     (const Conf__PutConfReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__put_conf_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__PutConfReq *
       conf__put_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__PutConfReq *)
     protobuf_c_message_unpack (&conf__put_conf_req__descriptor,
                                allocator, len, data);
}
void   conf__put_conf_req__free_unpacked
                     (Conf__PutConfReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__put_conf_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__put_conf_resp__init
                     (Conf__PutConfResp         *message)
{
  static const Conf__PutConfResp init_value = CONF__PUT_CONF_RESP__INIT;
  *message = init_value;
}
size_t conf__put_conf_resp__get_packed_size
                     (const Conf__PutConfResp *message)
{
  assert(message->base.descriptor == &conf__put_conf_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__put_conf_resp__pack
                     (const Conf__PutConfResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__put_conf_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__put_conf_resp__pack_to_buffer
                     (const Conf__PutConfResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__put_conf_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__PutConfResp *
       conf__put_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__PutConfResp *)
     protobuf_c_message_unpack (&conf__put_conf_resp__descriptor,
                                allocator, len, data);
}
void   conf__put_conf_resp__free_unpacked
                     (Conf__PutConfResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__put_conf_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__get_conf_req__init
                     (Conf__GetConfReq         *message)
{
  static const Conf__GetConfReq init_value = CONF__GET_CONF_REQ__INIT;
  *message = init_value;
}
size_t conf__get_conf_req__get_packed_size
                     (const Conf__GetConfReq *message)
{
  assert(message->base.descriptor == &conf__get_conf_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__get_conf_req__pack
                     (const Conf__GetConfReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__get_conf_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__get_conf_req__pack_to_buffer
                     (const Conf__GetConfReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__get_conf_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__GetConfReq *
       conf__get_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__GetConfReq *)
     protobuf_c_message_unpack (&conf__get_conf_req__descriptor,
                                allocator, len, data);
}
void   conf__get_conf_req__free_unpacked
                     (Conf__GetConfReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__get_conf_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__get_conf_resp__init
                     (Conf__GetConfResp         *message)
{
  static const Conf__GetConfResp init_value = CONF__GET_CONF_RESP__INIT;
  *message = init_value;
}
size_t conf__get_conf_resp__get_packed_size
                     (const Conf__GetConfResp *message)
{
  assert(message->base.descriptor == &conf__get_conf_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__get_conf_resp__pack
                     (const Conf__GetConfResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__get_conf_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__get_conf_resp__pack_to_buffer
                     (const Conf__GetConfResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__get_conf_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__GetConfResp *
       conf__get_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__GetConfResp *)
     protobuf_c_message_unpack (&conf__get_conf_resp__descriptor,
                                allocator, len, data);
}
void   conf__get_conf_resp__free_unpacked
                     (Conf__GetConfResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__get_conf_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__delete_conf_req__init
                     (Conf__DeleteConfReq         *message)
{
  static const Conf__DeleteConfReq init_value = CONF__DELETE_CONF_REQ__INIT;
  *message = init_value;
}
size_t conf__delete_conf_req__get_packed_size
                     (const Conf__DeleteConfReq *message)
{
  assert(message->base.descriptor == &conf__delete_conf_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__delete_conf_req__pack
                     (const Conf__DeleteConfReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__delete_conf_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__delete_conf_req__pack_to_buffer
                     (const Conf__DeleteConfReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__delete_conf_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__DeleteConfReq *
       conf__delete_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__DeleteConfReq *)
     protobuf_c_message_unpack (&conf__delete_conf_req__descriptor,
                                allocator, len, data);
}
void   conf__delete_conf_req__free_unpacked
                     (Conf__DeleteConfReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__delete_conf_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   conf__delete_conf_resp__init
                     (Conf__DeleteConfResp         *message)
{
  static const Conf__DeleteConfResp init_value = CONF__DELETE_CONF_RESP__INIT;
  *message = init_value;
}
size_t conf__delete_conf_resp__get_packed_size
                     (const Conf__DeleteConfResp *message)
{
  assert(message->base.descriptor == &conf__delete_conf_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t conf__delete_conf_resp__pack
                     (const Conf__DeleteConfResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &conf__delete_conf_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t conf__delete_conf_resp__pack_to_buffer
                     (const Conf__DeleteConfResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &conf__delete_conf_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Conf__DeleteConfResp *
       conf__delete_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Conf__DeleteConfResp *)
     protobuf_c_message_unpack (&conf__delete_conf_resp__descriptor,
                                allocator, len, data);
}
void   conf__delete_conf_resp__free_unpacked
                     (Conf__DeleteConfResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &conf__delete_conf_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor conf__create_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__CreateSchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__create_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange conf__create_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conf__create_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.CreateSchemaReq",
  "CreateSchemaReq",
  "Conf__CreateSchemaReq",
  "conf",
  sizeof(Conf__CreateSchemaReq),
  1,
  conf__create_schema_req__field_descriptors,
  conf__create_schema_req__field_indices_by_name,
  1,  conf__create_schema_req__number_ranges,
  (ProtobufCMessageInit) conf__create_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__create_schema_resp__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__CreateSchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Conf__CreateSchemaResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__CreateSchemaResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__create_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = msg */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange conf__create_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor conf__create_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.CreateSchemaResp",
  "CreateSchemaResp",
  "Conf__CreateSchemaResp",
  "conf",
  sizeof(Conf__CreateSchemaResp),
  3,
  conf__create_schema_resp__field_descriptors,
  conf__create_schema_resp__field_indices_by_name,
  1,  conf__create_schema_resp__number_ranges,
  (ProtobufCMessageInit) conf__create_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__query_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__QuerySchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__query_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange conf__query_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conf__query_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.QuerySchemaReq",
  "QuerySchemaReq",
  "Conf__QuerySchemaReq",
  "conf",
  sizeof(Conf__QuerySchemaReq),
  1,
  conf__query_schema_req__field_descriptors,
  conf__query_schema_req__field_indices_by_name,
  1,  conf__query_schema_req__number_ranges,
  (ProtobufCMessageInit) conf__query_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__query_schema_resp__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__QuerySchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Conf__QuerySchemaResp, n_confs),
    offsetof(Conf__QuerySchemaResp, confs),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__query_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = confs */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange conf__query_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor conf__query_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.QuerySchemaResp",
  "QuerySchemaResp",
  "Conf__QuerySchemaResp",
  "conf",
  sizeof(Conf__QuerySchemaResp),
  2,
  conf__query_schema_resp__field_descriptors,
  conf__query_schema_resp__field_indices_by_name,
  1,  conf__query_schema_resp__number_ranges,
  (ProtobufCMessageInit) conf__query_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__delete_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteSchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__delete_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange conf__delete_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor conf__delete_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.DeleteSchemaReq",
  "DeleteSchemaReq",
  "Conf__DeleteSchemaReq",
  "conf",
  sizeof(Conf__DeleteSchemaReq),
  1,
  conf__delete_schema_req__field_descriptors,
  conf__delete_schema_req__field_indices_by_name,
  1,  conf__delete_schema_req__number_ranges,
  (ProtobufCMessageInit) conf__delete_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__delete_schema_resp__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteSchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteSchemaResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__delete_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = msg */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange conf__delete_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor conf__delete_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.DeleteSchemaResp",
  "DeleteSchemaResp",
  "Conf__DeleteSchemaResp",
  "conf",
  sizeof(Conf__DeleteSchemaResp),
  2,
  conf__delete_schema_resp__field_descriptors,
  conf__delete_schema_resp__field_indices_by_name,
  1,  conf__delete_schema_resp__number_ranges,
  (ProtobufCMessageInit) conf__delete_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__put_conf_req__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__PutConfReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__PutConfReq, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__PutConfReq, conf_val),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__put_conf_req__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  2,   /* field[2] = conf_val */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange conf__put_conf_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor conf__put_conf_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.PutConfReq",
  "PutConfReq",
  "Conf__PutConfReq",
  "conf",
  sizeof(Conf__PutConfReq),
  3,
  conf__put_conf_req__field_descriptors,
  conf__put_conf_req__field_indices_by_name,
  1,  conf__put_conf_req__number_ranges,
  (ProtobufCMessageInit) conf__put_conf_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__put_conf_resp__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__PutConfResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__PutConfResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__put_conf_resp__field_indices_by_name[] = {
  1,   /* field[1] = msg */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange conf__put_conf_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor conf__put_conf_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.PutConfResp",
  "PutConfResp",
  "Conf__PutConfResp",
  "conf",
  sizeof(Conf__PutConfResp),
  2,
  conf__put_conf_resp__field_descriptors,
  conf__put_conf_resp__field_indices_by_name,
  1,  conf__put_conf_resp__number_ranges,
  (ProtobufCMessageInit) conf__put_conf_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__get_conf_req__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__GetConfReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__GetConfReq, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__get_conf_req__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange conf__get_conf_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor conf__get_conf_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.GetConfReq",
  "GetConfReq",
  "Conf__GetConfReq",
  "conf",
  sizeof(Conf__GetConfReq),
  2,
  conf__get_conf_req__field_descriptors,
  conf__get_conf_req__field_indices_by_name,
  1,  conf__get_conf_req__number_ranges,
  (ProtobufCMessageInit) conf__get_conf_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__get_conf_resp__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__GetConfResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__GetConfResp, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__GetConfResp, conf_val),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__get_conf_resp__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  2,   /* field[2] = conf_val */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange conf__get_conf_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor conf__get_conf_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.GetConfResp",
  "GetConfResp",
  "Conf__GetConfResp",
  "conf",
  sizeof(Conf__GetConfResp),
  3,
  conf__get_conf_resp__field_descriptors,
  conf__get_conf_resp__field_indices_by_name,
  1,  conf__get_conf_resp__number_ranges,
  (ProtobufCMessageInit) conf__get_conf_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__delete_conf_req__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteConfReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteConfReq, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__delete_conf_req__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange conf__delete_conf_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor conf__delete_conf_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.DeleteConfReq",
  "DeleteConfReq",
  "Conf__DeleteConfReq",
  "conf",
  sizeof(Conf__DeleteConfReq),
  2,
  conf__delete_conf_req__field_descriptors,
  conf__delete_conf_req__field_indices_by_name,
  1,  conf__delete_conf_req__number_ranges,
  (ProtobufCMessageInit) conf__delete_conf_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor conf__delete_conf_resp__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteConfResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteConfResp, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Conf__DeleteConfResp, conf_val),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned conf__delete_conf_resp__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  2,   /* field[2] = conf_val */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange conf__delete_conf_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor conf__delete_conf_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "conf.DeleteConfResp",
  "DeleteConfResp",
  "Conf__DeleteConfResp",
  "conf",
  sizeof(Conf__DeleteConfResp),
  3,
  conf__delete_conf_resp__field_descriptors,
  conf__delete_conf_resp__field_indices_by_name,
  1,  conf__delete_conf_resp__number_ranges,
  (ProtobufCMessageInit) conf__delete_conf_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
