/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: kv.proto */

#ifndef PROTOBUF_C_kv_2eproto__INCLUDED
#define PROTOBUF_C_kv_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Kv__CreateSchemaReq Kv__CreateSchemaReq;
typedef struct _Kv__CreateSchemaResp Kv__CreateSchemaResp;
typedef struct _Kv__QuerySchemaReq Kv__QuerySchemaReq;
typedef struct _Kv__QuerySchemaResp Kv__QuerySchemaResp;
typedef struct _Kv__DeleteSchemaReq Kv__DeleteSchemaReq;
typedef struct _Kv__DeleteSchemaResp Kv__DeleteSchemaResp;
typedef struct _Kv__PutConfReq Kv__PutConfReq;
typedef struct _Kv__PutConfResp Kv__PutConfResp;
typedef struct _Kv__GetConfReq Kv__GetConfReq;
typedef struct _Kv__GetConfResp Kv__GetConfResp;
typedef struct _Kv__DeleteConfReq Kv__DeleteConfReq;
typedef struct _Kv__DeleteConfResp Kv__DeleteConfResp;


/* --- enums --- */


/* --- messages --- */

struct  _Kv__CreateSchemaReq
{
  ProtobufCMessage base;
  char *name;
};
#define KV__CREATE_SCHEMA_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__create_schema_req__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Kv__CreateSchemaResp
{
  ProtobufCMessage base;
  char *name;
  int32_t code;
  char *msg;
};
#define KV__CREATE_SCHEMA_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__create_schema_resp__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  _Kv__QuerySchemaReq
{
  ProtobufCMessage base;
  char *name;
};
#define KV__QUERY_SCHEMA_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__query_schema_req__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Kv__QuerySchemaResp
{
  ProtobufCMessage base;
  char *name;
  size_t n_confs;
  char **confs;
};
#define KV__QUERY_SCHEMA_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__query_schema_resp__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _Kv__DeleteSchemaReq
{
  ProtobufCMessage base;
  char *name;
};
#define KV__DELETE_SCHEMA_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__delete_schema_req__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Kv__DeleteSchemaResp
{
  ProtobufCMessage base;
  char *name;
  char *msg;
};
#define KV__DELETE_SCHEMA_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__delete_schema_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Kv__PutConfReq
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
  char *conf_val;
};
#define KV__PUT_CONF_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__put_conf_req__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Kv__PutConfResp
{
  ProtobufCMessage base;
  char *schema_name;
  char *msg;
};
#define KV__PUT_CONF_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__put_conf_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Kv__GetConfReq
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
};
#define KV__GET_CONF_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__get_conf_req__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Kv__GetConfResp
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
  char *conf_val;
};
#define KV__GET_CONF_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__get_conf_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Kv__DeleteConfReq
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
};
#define KV__DELETE_CONF_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__delete_conf_req__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Kv__DeleteConfResp
{
  ProtobufCMessage base;
  char *schema_name;
  char *conf_key;
  char *conf_val;
};
#define KV__DELETE_CONF_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__delete_conf_resp__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Kv__CreateSchemaReq methods */
void   kv__create_schema_req__init
                     (Kv__CreateSchemaReq         *message);
size_t kv__create_schema_req__get_packed_size
                     (const Kv__CreateSchemaReq   *message);
size_t kv__create_schema_req__pack
                     (const Kv__CreateSchemaReq   *message,
                      uint8_t             *out);
size_t kv__create_schema_req__pack_to_buffer
                     (const Kv__CreateSchemaReq   *message,
                      ProtobufCBuffer     *buffer);
Kv__CreateSchemaReq *
       kv__create_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__create_schema_req__free_unpacked
                     (Kv__CreateSchemaReq *message,
                      ProtobufCAllocator *allocator);
/* Kv__CreateSchemaResp methods */
void   kv__create_schema_resp__init
                     (Kv__CreateSchemaResp         *message);
size_t kv__create_schema_resp__get_packed_size
                     (const Kv__CreateSchemaResp   *message);
size_t kv__create_schema_resp__pack
                     (const Kv__CreateSchemaResp   *message,
                      uint8_t             *out);
size_t kv__create_schema_resp__pack_to_buffer
                     (const Kv__CreateSchemaResp   *message,
                      ProtobufCBuffer     *buffer);
Kv__CreateSchemaResp *
       kv__create_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__create_schema_resp__free_unpacked
                     (Kv__CreateSchemaResp *message,
                      ProtobufCAllocator *allocator);
/* Kv__QuerySchemaReq methods */
void   kv__query_schema_req__init
                     (Kv__QuerySchemaReq         *message);
size_t kv__query_schema_req__get_packed_size
                     (const Kv__QuerySchemaReq   *message);
size_t kv__query_schema_req__pack
                     (const Kv__QuerySchemaReq   *message,
                      uint8_t             *out);
size_t kv__query_schema_req__pack_to_buffer
                     (const Kv__QuerySchemaReq   *message,
                      ProtobufCBuffer     *buffer);
Kv__QuerySchemaReq *
       kv__query_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__query_schema_req__free_unpacked
                     (Kv__QuerySchemaReq *message,
                      ProtobufCAllocator *allocator);
/* Kv__QuerySchemaResp methods */
void   kv__query_schema_resp__init
                     (Kv__QuerySchemaResp         *message);
size_t kv__query_schema_resp__get_packed_size
                     (const Kv__QuerySchemaResp   *message);
size_t kv__query_schema_resp__pack
                     (const Kv__QuerySchemaResp   *message,
                      uint8_t             *out);
size_t kv__query_schema_resp__pack_to_buffer
                     (const Kv__QuerySchemaResp   *message,
                      ProtobufCBuffer     *buffer);
Kv__QuerySchemaResp *
       kv__query_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__query_schema_resp__free_unpacked
                     (Kv__QuerySchemaResp *message,
                      ProtobufCAllocator *allocator);
/* Kv__DeleteSchemaReq methods */
void   kv__delete_schema_req__init
                     (Kv__DeleteSchemaReq         *message);
size_t kv__delete_schema_req__get_packed_size
                     (const Kv__DeleteSchemaReq   *message);
size_t kv__delete_schema_req__pack
                     (const Kv__DeleteSchemaReq   *message,
                      uint8_t             *out);
size_t kv__delete_schema_req__pack_to_buffer
                     (const Kv__DeleteSchemaReq   *message,
                      ProtobufCBuffer     *buffer);
Kv__DeleteSchemaReq *
       kv__delete_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__delete_schema_req__free_unpacked
                     (Kv__DeleteSchemaReq *message,
                      ProtobufCAllocator *allocator);
/* Kv__DeleteSchemaResp methods */
void   kv__delete_schema_resp__init
                     (Kv__DeleteSchemaResp         *message);
size_t kv__delete_schema_resp__get_packed_size
                     (const Kv__DeleteSchemaResp   *message);
size_t kv__delete_schema_resp__pack
                     (const Kv__DeleteSchemaResp   *message,
                      uint8_t             *out);
size_t kv__delete_schema_resp__pack_to_buffer
                     (const Kv__DeleteSchemaResp   *message,
                      ProtobufCBuffer     *buffer);
Kv__DeleteSchemaResp *
       kv__delete_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__delete_schema_resp__free_unpacked
                     (Kv__DeleteSchemaResp *message,
                      ProtobufCAllocator *allocator);
/* Kv__PutConfReq methods */
void   kv__put_conf_req__init
                     (Kv__PutConfReq         *message);
size_t kv__put_conf_req__get_packed_size
                     (const Kv__PutConfReq   *message);
size_t kv__put_conf_req__pack
                     (const Kv__PutConfReq   *message,
                      uint8_t             *out);
size_t kv__put_conf_req__pack_to_buffer
                     (const Kv__PutConfReq   *message,
                      ProtobufCBuffer     *buffer);
Kv__PutConfReq *
       kv__put_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__put_conf_req__free_unpacked
                     (Kv__PutConfReq *message,
                      ProtobufCAllocator *allocator);
/* Kv__PutConfResp methods */
void   kv__put_conf_resp__init
                     (Kv__PutConfResp         *message);
size_t kv__put_conf_resp__get_packed_size
                     (const Kv__PutConfResp   *message);
size_t kv__put_conf_resp__pack
                     (const Kv__PutConfResp   *message,
                      uint8_t             *out);
size_t kv__put_conf_resp__pack_to_buffer
                     (const Kv__PutConfResp   *message,
                      ProtobufCBuffer     *buffer);
Kv__PutConfResp *
       kv__put_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__put_conf_resp__free_unpacked
                     (Kv__PutConfResp *message,
                      ProtobufCAllocator *allocator);
/* Kv__GetConfReq methods */
void   kv__get_conf_req__init
                     (Kv__GetConfReq         *message);
size_t kv__get_conf_req__get_packed_size
                     (const Kv__GetConfReq   *message);
size_t kv__get_conf_req__pack
                     (const Kv__GetConfReq   *message,
                      uint8_t             *out);
size_t kv__get_conf_req__pack_to_buffer
                     (const Kv__GetConfReq   *message,
                      ProtobufCBuffer     *buffer);
Kv__GetConfReq *
       kv__get_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__get_conf_req__free_unpacked
                     (Kv__GetConfReq *message,
                      ProtobufCAllocator *allocator);
/* Kv__GetConfResp methods */
void   kv__get_conf_resp__init
                     (Kv__GetConfResp         *message);
size_t kv__get_conf_resp__get_packed_size
                     (const Kv__GetConfResp   *message);
size_t kv__get_conf_resp__pack
                     (const Kv__GetConfResp   *message,
                      uint8_t             *out);
size_t kv__get_conf_resp__pack_to_buffer
                     (const Kv__GetConfResp   *message,
                      ProtobufCBuffer     *buffer);
Kv__GetConfResp *
       kv__get_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__get_conf_resp__free_unpacked
                     (Kv__GetConfResp *message,
                      ProtobufCAllocator *allocator);
/* Kv__DeleteConfReq methods */
void   kv__delete_conf_req__init
                     (Kv__DeleteConfReq         *message);
size_t kv__delete_conf_req__get_packed_size
                     (const Kv__DeleteConfReq   *message);
size_t kv__delete_conf_req__pack
                     (const Kv__DeleteConfReq   *message,
                      uint8_t             *out);
size_t kv__delete_conf_req__pack_to_buffer
                     (const Kv__DeleteConfReq   *message,
                      ProtobufCBuffer     *buffer);
Kv__DeleteConfReq *
       kv__delete_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__delete_conf_req__free_unpacked
                     (Kv__DeleteConfReq *message,
                      ProtobufCAllocator *allocator);
/* Kv__DeleteConfResp methods */
void   kv__delete_conf_resp__init
                     (Kv__DeleteConfResp         *message);
size_t kv__delete_conf_resp__get_packed_size
                     (const Kv__DeleteConfResp   *message);
size_t kv__delete_conf_resp__pack
                     (const Kv__DeleteConfResp   *message,
                      uint8_t             *out);
size_t kv__delete_conf_resp__pack_to_buffer
                     (const Kv__DeleteConfResp   *message,
                      ProtobufCBuffer     *buffer);
Kv__DeleteConfResp *
       kv__delete_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__delete_conf_resp__free_unpacked
                     (Kv__DeleteConfResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Kv__CreateSchemaReq_Closure)
                 (const Kv__CreateSchemaReq *message,
                  void *closure_data);
typedef void (*Kv__CreateSchemaResp_Closure)
                 (const Kv__CreateSchemaResp *message,
                  void *closure_data);
typedef void (*Kv__QuerySchemaReq_Closure)
                 (const Kv__QuerySchemaReq *message,
                  void *closure_data);
typedef void (*Kv__QuerySchemaResp_Closure)
                 (const Kv__QuerySchemaResp *message,
                  void *closure_data);
typedef void (*Kv__DeleteSchemaReq_Closure)
                 (const Kv__DeleteSchemaReq *message,
                  void *closure_data);
typedef void (*Kv__DeleteSchemaResp_Closure)
                 (const Kv__DeleteSchemaResp *message,
                  void *closure_data);
typedef void (*Kv__PutConfReq_Closure)
                 (const Kv__PutConfReq *message,
                  void *closure_data);
typedef void (*Kv__PutConfResp_Closure)
                 (const Kv__PutConfResp *message,
                  void *closure_data);
typedef void (*Kv__GetConfReq_Closure)
                 (const Kv__GetConfReq *message,
                  void *closure_data);
typedef void (*Kv__GetConfResp_Closure)
                 (const Kv__GetConfResp *message,
                  void *closure_data);
typedef void (*Kv__DeleteConfReq_Closure)
                 (const Kv__DeleteConfReq *message,
                  void *closure_data);
typedef void (*Kv__DeleteConfResp_Closure)
                 (const Kv__DeleteConfResp *message,
                  void *closure_data);

/* --- services --- */

typedef struct _Kv__KvService_Service Kv__KvService_Service;
struct _Kv__KvService_Service
{
  ProtobufCService base;
  void (*create_schema)(Kv__KvService_Service *service,
                        const Kv__CreateSchemaReq *input,
                        Kv__CreateSchemaResp_Closure closure,
                        void *closure_data);
  void (*query_schema)(Kv__KvService_Service *service,
                       const Kv__QuerySchemaReq *input,
                       Kv__QuerySchemaResp_Closure closure,
                       void *closure_data);
  void (*delete_schema)(Kv__KvService_Service *service,
                        const Kv__DeleteSchemaReq *input,
                        Kv__DeleteSchemaResp_Closure closure,
                        void *closure_data);
  void (*put_conf)(Kv__KvService_Service *service,
                   const Kv__PutConfReq *input,
                   Kv__PutConfResp_Closure closure,
                   void *closure_data);
  void (*get_conf)(Kv__KvService_Service *service,
                   const Kv__GetConfReq *input,
                   Kv__GetConfResp_Closure closure,
                   void *closure_data);
  void (*delete_conf)(Kv__KvService_Service *service,
                      const Kv__DeleteConfReq *input,
                      Kv__DeleteConfResp_Closure closure,
                      void *closure_data);
};
typedef void (*Kv__KvService_ServiceDestroy)(Kv__KvService_Service *);
void kv__kv_service__init (Kv__KvService_Service *service,
                           Kv__KvService_ServiceDestroy destroy);
#define KV__KV_SERVICE__BASE_INIT \
    { &kv__kv_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define KV__KV_SERVICE__INIT(function_prefix__) \
    { KV__KV_SERVICE__BASE_INIT,\
      function_prefix__ ## create_schema,\
      function_prefix__ ## query_schema,\
      function_prefix__ ## delete_schema,\
      function_prefix__ ## put_conf,\
      function_prefix__ ## get_conf,\
      function_prefix__ ## delete_conf  }
void kv__kv_service__create_schema(ProtobufCService *service,
                                   const Kv__CreateSchemaReq *input,
                                   Kv__CreateSchemaResp_Closure closure,
                                   void *closure_data);
void kv__kv_service__query_schema(ProtobufCService *service,
                                  const Kv__QuerySchemaReq *input,
                                  Kv__QuerySchemaResp_Closure closure,
                                  void *closure_data);
void kv__kv_service__delete_schema(ProtobufCService *service,
                                   const Kv__DeleteSchemaReq *input,
                                   Kv__DeleteSchemaResp_Closure closure,
                                   void *closure_data);
void kv__kv_service__put_conf(ProtobufCService *service,
                              const Kv__PutConfReq *input,
                              Kv__PutConfResp_Closure closure,
                              void *closure_data);
void kv__kv_service__get_conf(ProtobufCService *service,
                              const Kv__GetConfReq *input,
                              Kv__GetConfResp_Closure closure,
                              void *closure_data);
void kv__kv_service__delete_conf(ProtobufCService *service,
                                 const Kv__DeleteConfReq *input,
                                 Kv__DeleteConfResp_Closure closure,
                                 void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor kv__create_schema_req__descriptor;
extern const ProtobufCMessageDescriptor kv__create_schema_resp__descriptor;
extern const ProtobufCMessageDescriptor kv__query_schema_req__descriptor;
extern const ProtobufCMessageDescriptor kv__query_schema_resp__descriptor;
extern const ProtobufCMessageDescriptor kv__delete_schema_req__descriptor;
extern const ProtobufCMessageDescriptor kv__delete_schema_resp__descriptor;
extern const ProtobufCMessageDescriptor kv__put_conf_req__descriptor;
extern const ProtobufCMessageDescriptor kv__put_conf_resp__descriptor;
extern const ProtobufCMessageDescriptor kv__get_conf_req__descriptor;
extern const ProtobufCMessageDescriptor kv__get_conf_resp__descriptor;
extern const ProtobufCMessageDescriptor kv__delete_conf_req__descriptor;
extern const ProtobufCMessageDescriptor kv__delete_conf_resp__descriptor;
extern const ProtobufCServiceDescriptor kv__kv_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_kv_2eproto__INCLUDED */
