/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: kv.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "kv.pb-c.h"
void   kv__create_schema_req__init
                     (Kv__CreateSchemaReq         *message)
{
  static const Kv__CreateSchemaReq init_value = KV__CREATE_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t kv__create_schema_req__get_packed_size
                     (const Kv__CreateSchemaReq *message)
{
  assert(message->base.descriptor == &kv__create_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__create_schema_req__pack
                     (const Kv__CreateSchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__create_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__create_schema_req__pack_to_buffer
                     (const Kv__CreateSchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__create_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__CreateSchemaReq *
       kv__create_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__CreateSchemaReq *)
     protobuf_c_message_unpack (&kv__create_schema_req__descriptor,
                                allocator, len, data);
}
void   kv__create_schema_req__free_unpacked
                     (Kv__CreateSchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__create_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__create_schema_resp__init
                     (Kv__CreateSchemaResp         *message)
{
  static const Kv__CreateSchemaResp init_value = KV__CREATE_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t kv__create_schema_resp__get_packed_size
                     (const Kv__CreateSchemaResp *message)
{
  assert(message->base.descriptor == &kv__create_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__create_schema_resp__pack
                     (const Kv__CreateSchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__create_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__create_schema_resp__pack_to_buffer
                     (const Kv__CreateSchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__create_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__CreateSchemaResp *
       kv__create_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__CreateSchemaResp *)
     protobuf_c_message_unpack (&kv__create_schema_resp__descriptor,
                                allocator, len, data);
}
void   kv__create_schema_resp__free_unpacked
                     (Kv__CreateSchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__create_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__query_schema_req__init
                     (Kv__QuerySchemaReq         *message)
{
  static const Kv__QuerySchemaReq init_value = KV__QUERY_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t kv__query_schema_req__get_packed_size
                     (const Kv__QuerySchemaReq *message)
{
  assert(message->base.descriptor == &kv__query_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__query_schema_req__pack
                     (const Kv__QuerySchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__query_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__query_schema_req__pack_to_buffer
                     (const Kv__QuerySchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__query_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__QuerySchemaReq *
       kv__query_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__QuerySchemaReq *)
     protobuf_c_message_unpack (&kv__query_schema_req__descriptor,
                                allocator, len, data);
}
void   kv__query_schema_req__free_unpacked
                     (Kv__QuerySchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__query_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__query_schema_resp__init
                     (Kv__QuerySchemaResp         *message)
{
  static const Kv__QuerySchemaResp init_value = KV__QUERY_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t kv__query_schema_resp__get_packed_size
                     (const Kv__QuerySchemaResp *message)
{
  assert(message->base.descriptor == &kv__query_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__query_schema_resp__pack
                     (const Kv__QuerySchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__query_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__query_schema_resp__pack_to_buffer
                     (const Kv__QuerySchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__query_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__QuerySchemaResp *
       kv__query_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__QuerySchemaResp *)
     protobuf_c_message_unpack (&kv__query_schema_resp__descriptor,
                                allocator, len, data);
}
void   kv__query_schema_resp__free_unpacked
                     (Kv__QuerySchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__query_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__delete_schema_req__init
                     (Kv__DeleteSchemaReq         *message)
{
  static const Kv__DeleteSchemaReq init_value = KV__DELETE_SCHEMA_REQ__INIT;
  *message = init_value;
}
size_t kv__delete_schema_req__get_packed_size
                     (const Kv__DeleteSchemaReq *message)
{
  assert(message->base.descriptor == &kv__delete_schema_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__delete_schema_req__pack
                     (const Kv__DeleteSchemaReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__delete_schema_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__delete_schema_req__pack_to_buffer
                     (const Kv__DeleteSchemaReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__delete_schema_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__DeleteSchemaReq *
       kv__delete_schema_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__DeleteSchemaReq *)
     protobuf_c_message_unpack (&kv__delete_schema_req__descriptor,
                                allocator, len, data);
}
void   kv__delete_schema_req__free_unpacked
                     (Kv__DeleteSchemaReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__delete_schema_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__delete_schema_resp__init
                     (Kv__DeleteSchemaResp         *message)
{
  static const Kv__DeleteSchemaResp init_value = KV__DELETE_SCHEMA_RESP__INIT;
  *message = init_value;
}
size_t kv__delete_schema_resp__get_packed_size
                     (const Kv__DeleteSchemaResp *message)
{
  assert(message->base.descriptor == &kv__delete_schema_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__delete_schema_resp__pack
                     (const Kv__DeleteSchemaResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__delete_schema_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__delete_schema_resp__pack_to_buffer
                     (const Kv__DeleteSchemaResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__delete_schema_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__DeleteSchemaResp *
       kv__delete_schema_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__DeleteSchemaResp *)
     protobuf_c_message_unpack (&kv__delete_schema_resp__descriptor,
                                allocator, len, data);
}
void   kv__delete_schema_resp__free_unpacked
                     (Kv__DeleteSchemaResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__delete_schema_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__put_conf_req__init
                     (Kv__PutConfReq         *message)
{
  static const Kv__PutConfReq init_value = KV__PUT_CONF_REQ__INIT;
  *message = init_value;
}
size_t kv__put_conf_req__get_packed_size
                     (const Kv__PutConfReq *message)
{
  assert(message->base.descriptor == &kv__put_conf_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__put_conf_req__pack
                     (const Kv__PutConfReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__put_conf_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__put_conf_req__pack_to_buffer
                     (const Kv__PutConfReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__put_conf_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__PutConfReq *
       kv__put_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__PutConfReq *)
     protobuf_c_message_unpack (&kv__put_conf_req__descriptor,
                                allocator, len, data);
}
void   kv__put_conf_req__free_unpacked
                     (Kv__PutConfReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__put_conf_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__put_conf_resp__init
                     (Kv__PutConfResp         *message)
{
  static const Kv__PutConfResp init_value = KV__PUT_CONF_RESP__INIT;
  *message = init_value;
}
size_t kv__put_conf_resp__get_packed_size
                     (const Kv__PutConfResp *message)
{
  assert(message->base.descriptor == &kv__put_conf_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__put_conf_resp__pack
                     (const Kv__PutConfResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__put_conf_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__put_conf_resp__pack_to_buffer
                     (const Kv__PutConfResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__put_conf_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__PutConfResp *
       kv__put_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__PutConfResp *)
     protobuf_c_message_unpack (&kv__put_conf_resp__descriptor,
                                allocator, len, data);
}
void   kv__put_conf_resp__free_unpacked
                     (Kv__PutConfResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__put_conf_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__get_conf_req__init
                     (Kv__GetConfReq         *message)
{
  static const Kv__GetConfReq init_value = KV__GET_CONF_REQ__INIT;
  *message = init_value;
}
size_t kv__get_conf_req__get_packed_size
                     (const Kv__GetConfReq *message)
{
  assert(message->base.descriptor == &kv__get_conf_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__get_conf_req__pack
                     (const Kv__GetConfReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__get_conf_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__get_conf_req__pack_to_buffer
                     (const Kv__GetConfReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__get_conf_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__GetConfReq *
       kv__get_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__GetConfReq *)
     protobuf_c_message_unpack (&kv__get_conf_req__descriptor,
                                allocator, len, data);
}
void   kv__get_conf_req__free_unpacked
                     (Kv__GetConfReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__get_conf_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__get_conf_resp__init
                     (Kv__GetConfResp         *message)
{
  static const Kv__GetConfResp init_value = KV__GET_CONF_RESP__INIT;
  *message = init_value;
}
size_t kv__get_conf_resp__get_packed_size
                     (const Kv__GetConfResp *message)
{
  assert(message->base.descriptor == &kv__get_conf_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__get_conf_resp__pack
                     (const Kv__GetConfResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__get_conf_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__get_conf_resp__pack_to_buffer
                     (const Kv__GetConfResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__get_conf_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__GetConfResp *
       kv__get_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__GetConfResp *)
     protobuf_c_message_unpack (&kv__get_conf_resp__descriptor,
                                allocator, len, data);
}
void   kv__get_conf_resp__free_unpacked
                     (Kv__GetConfResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__get_conf_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__delete_conf_req__init
                     (Kv__DeleteConfReq         *message)
{
  static const Kv__DeleteConfReq init_value = KV__DELETE_CONF_REQ__INIT;
  *message = init_value;
}
size_t kv__delete_conf_req__get_packed_size
                     (const Kv__DeleteConfReq *message)
{
  assert(message->base.descriptor == &kv__delete_conf_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__delete_conf_req__pack
                     (const Kv__DeleteConfReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__delete_conf_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__delete_conf_req__pack_to_buffer
                     (const Kv__DeleteConfReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__delete_conf_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__DeleteConfReq *
       kv__delete_conf_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__DeleteConfReq *)
     protobuf_c_message_unpack (&kv__delete_conf_req__descriptor,
                                allocator, len, data);
}
void   kv__delete_conf_req__free_unpacked
                     (Kv__DeleteConfReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__delete_conf_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__delete_conf_resp__init
                     (Kv__DeleteConfResp         *message)
{
  static const Kv__DeleteConfResp init_value = KV__DELETE_CONF_RESP__INIT;
  *message = init_value;
}
size_t kv__delete_conf_resp__get_packed_size
                     (const Kv__DeleteConfResp *message)
{
  assert(message->base.descriptor == &kv__delete_conf_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__delete_conf_resp__pack
                     (const Kv__DeleteConfResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__delete_conf_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__delete_conf_resp__pack_to_buffer
                     (const Kv__DeleteConfResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__delete_conf_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__DeleteConfResp *
       kv__delete_conf_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__DeleteConfResp *)
     protobuf_c_message_unpack (&kv__delete_conf_resp__descriptor,
                                allocator, len, data);
}
void   kv__delete_conf_resp__free_unpacked
                     (Kv__DeleteConfResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__delete_conf_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor kv__create_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__CreateSchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__create_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange kv__create_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor kv__create_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.CreateSchemaReq",
  "CreateSchemaReq",
  "Kv__CreateSchemaReq",
  "kv",
  sizeof(Kv__CreateSchemaReq),
  1,
  kv__create_schema_req__field_descriptors,
  kv__create_schema_req__field_indices_by_name,
  1,  kv__create_schema_req__number_ranges,
  (ProtobufCMessageInit) kv__create_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__create_schema_resp__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__CreateSchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Kv__CreateSchemaResp, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__CreateSchemaResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__create_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = msg */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange kv__create_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor kv__create_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.CreateSchemaResp",
  "CreateSchemaResp",
  "Kv__CreateSchemaResp",
  "kv",
  sizeof(Kv__CreateSchemaResp),
  3,
  kv__create_schema_resp__field_descriptors,
  kv__create_schema_resp__field_indices_by_name,
  1,  kv__create_schema_resp__number_ranges,
  (ProtobufCMessageInit) kv__create_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__query_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__QuerySchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__query_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange kv__query_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor kv__query_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.QuerySchemaReq",
  "QuerySchemaReq",
  "Kv__QuerySchemaReq",
  "kv",
  sizeof(Kv__QuerySchemaReq),
  1,
  kv__query_schema_req__field_descriptors,
  kv__query_schema_req__field_indices_by_name,
  1,  kv__query_schema_req__number_ranges,
  (ProtobufCMessageInit) kv__query_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__query_schema_resp__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__QuerySchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Kv__QuerySchemaResp, n_confs),
    offsetof(Kv__QuerySchemaResp, confs),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__query_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = confs */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange kv__query_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kv__query_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.QuerySchemaResp",
  "QuerySchemaResp",
  "Kv__QuerySchemaResp",
  "kv",
  sizeof(Kv__QuerySchemaResp),
  2,
  kv__query_schema_resp__field_descriptors,
  kv__query_schema_resp__field_indices_by_name,
  1,  kv__query_schema_resp__number_ranges,
  (ProtobufCMessageInit) kv__query_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__delete_schema_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteSchemaReq, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__delete_schema_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange kv__delete_schema_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor kv__delete_schema_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.DeleteSchemaReq",
  "DeleteSchemaReq",
  "Kv__DeleteSchemaReq",
  "kv",
  sizeof(Kv__DeleteSchemaReq),
  1,
  kv__delete_schema_req__field_descriptors,
  kv__delete_schema_req__field_indices_by_name,
  1,  kv__delete_schema_req__number_ranges,
  (ProtobufCMessageInit) kv__delete_schema_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__delete_schema_resp__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteSchemaResp, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteSchemaResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__delete_schema_resp__field_indices_by_name[] = {
  1,   /* field[1] = msg */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange kv__delete_schema_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kv__delete_schema_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.DeleteSchemaResp",
  "DeleteSchemaResp",
  "Kv__DeleteSchemaResp",
  "kv",
  sizeof(Kv__DeleteSchemaResp),
  2,
  kv__delete_schema_resp__field_descriptors,
  kv__delete_schema_resp__field_indices_by_name,
  1,  kv__delete_schema_resp__number_ranges,
  (ProtobufCMessageInit) kv__delete_schema_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__put_conf_req__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__PutConfReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__PutConfReq, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__PutConfReq, conf_val),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__put_conf_req__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  2,   /* field[2] = conf_val */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange kv__put_conf_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor kv__put_conf_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.PutConfReq",
  "PutConfReq",
  "Kv__PutConfReq",
  "kv",
  sizeof(Kv__PutConfReq),
  3,
  kv__put_conf_req__field_descriptors,
  kv__put_conf_req__field_indices_by_name,
  1,  kv__put_conf_req__number_ranges,
  (ProtobufCMessageInit) kv__put_conf_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__put_conf_resp__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__PutConfResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__PutConfResp, msg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__put_conf_resp__field_indices_by_name[] = {
  1,   /* field[1] = msg */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange kv__put_conf_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kv__put_conf_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.PutConfResp",
  "PutConfResp",
  "Kv__PutConfResp",
  "kv",
  sizeof(Kv__PutConfResp),
  2,
  kv__put_conf_resp__field_descriptors,
  kv__put_conf_resp__field_indices_by_name,
  1,  kv__put_conf_resp__number_ranges,
  (ProtobufCMessageInit) kv__put_conf_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__get_conf_req__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__GetConfReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__GetConfReq, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__get_conf_req__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange kv__get_conf_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kv__get_conf_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.GetConfReq",
  "GetConfReq",
  "Kv__GetConfReq",
  "kv",
  sizeof(Kv__GetConfReq),
  2,
  kv__get_conf_req__field_descriptors,
  kv__get_conf_req__field_indices_by_name,
  1,  kv__get_conf_req__number_ranges,
  (ProtobufCMessageInit) kv__get_conf_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__get_conf_resp__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__GetConfResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__GetConfResp, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__GetConfResp, conf_val),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__get_conf_resp__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  2,   /* field[2] = conf_val */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange kv__get_conf_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor kv__get_conf_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.GetConfResp",
  "GetConfResp",
  "Kv__GetConfResp",
  "kv",
  sizeof(Kv__GetConfResp),
  3,
  kv__get_conf_resp__field_descriptors,
  kv__get_conf_resp__field_indices_by_name,
  1,  kv__get_conf_resp__number_ranges,
  (ProtobufCMessageInit) kv__get_conf_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__delete_conf_req__field_descriptors[2] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteConfReq, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteConfReq, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__delete_conf_req__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange kv__delete_conf_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kv__delete_conf_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.DeleteConfReq",
  "DeleteConfReq",
  "Kv__DeleteConfReq",
  "kv",
  sizeof(Kv__DeleteConfReq),
  2,
  kv__delete_conf_req__field_descriptors,
  kv__delete_conf_req__field_indices_by_name,
  1,  kv__delete_conf_req__number_ranges,
  (ProtobufCMessageInit) kv__delete_conf_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__delete_conf_resp__field_descriptors[3] =
{
  {
    "schema_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteConfResp, schema_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteConfResp, conf_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf_val",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__DeleteConfResp, conf_val),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__delete_conf_resp__field_indices_by_name[] = {
  1,   /* field[1] = conf_key */
  2,   /* field[2] = conf_val */
  0,   /* field[0] = schema_name */
};
static const ProtobufCIntRange kv__delete_conf_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor kv__delete_conf_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.DeleteConfResp",
  "DeleteConfResp",
  "Kv__DeleteConfResp",
  "kv",
  sizeof(Kv__DeleteConfResp),
  3,
  kv__delete_conf_resp__field_descriptors,
  kv__delete_conf_resp__field_indices_by_name,
  1,  kv__delete_conf_resp__number_ranges,
  (ProtobufCMessageInit) kv__delete_conf_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor kv__kv_service__method_descriptors[6] =
{
  { "CreateSchema", &kv__create_schema_req__descriptor, &kv__create_schema_resp__descriptor },
  { "QuerySchema", &kv__query_schema_req__descriptor, &kv__query_schema_resp__descriptor },
  { "DeleteSchema", &kv__delete_schema_req__descriptor, &kv__delete_schema_resp__descriptor },
  { "PutConf", &kv__put_conf_req__descriptor, &kv__put_conf_resp__descriptor },
  { "GetConf", &kv__get_conf_req__descriptor, &kv__get_conf_resp__descriptor },
  { "DeleteConf", &kv__delete_conf_req__descriptor, &kv__delete_conf_resp__descriptor },
};
const unsigned kv__kv_service__method_indices_by_name[] = {
  0,        /* CreateSchema */
  5,        /* DeleteConf */
  2,        /* DeleteSchema */
  4,        /* GetConf */
  3,        /* PutConf */
  1         /* QuerySchema */
};
const ProtobufCServiceDescriptor kv__kv_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "kv.KvService",
  "KvService",
  "Kv__KvService",
  "kv",
  6,
  kv__kv_service__method_descriptors,
  kv__kv_service__method_indices_by_name
};
void kv__kv_service__create_schema(ProtobufCService *service,
                                   const Kv__CreateSchemaReq *input,
                                   Kv__CreateSchemaResp_Closure closure,
                                   void *closure_data)
{
  assert(service->descriptor == &kv__kv_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void kv__kv_service__query_schema(ProtobufCService *service,
                                  const Kv__QuerySchemaReq *input,
                                  Kv__QuerySchemaResp_Closure closure,
                                  void *closure_data)
{
  assert(service->descriptor == &kv__kv_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void kv__kv_service__delete_schema(ProtobufCService *service,
                                   const Kv__DeleteSchemaReq *input,
                                   Kv__DeleteSchemaResp_Closure closure,
                                   void *closure_data)
{
  assert(service->descriptor == &kv__kv_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void kv__kv_service__put_conf(ProtobufCService *service,
                              const Kv__PutConfReq *input,
                              Kv__PutConfResp_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &kv__kv_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void kv__kv_service__get_conf(ProtobufCService *service,
                              const Kv__GetConfReq *input,
                              Kv__GetConfResp_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &kv__kv_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void kv__kv_service__delete_conf(ProtobufCService *service,
                                 const Kv__DeleteConfReq *input,
                                 Kv__DeleteConfResp_Closure closure,
                                 void *closure_data)
{
  assert(service->descriptor == &kv__kv_service__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void kv__kv_service__init (Kv__KvService_Service *service,
                           Kv__KvService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &kv__kv_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
